### ISSUE TITLE
Plot examples in README

### ISSUE THREAD

**Issue by cimentadaj** [m-clark/visibly#1]
@m-clark thanks for package, just had a look! Since this is pretty much a package about visualization, it would be really handy if the `README` had some brief examples of plots. It took me a while to go to the vignette and rerun the examples just to see how they looked like.

Thanks again, they look really cool!

**Comment by m-clark** [comment]
Sure will, I did initially have some code on the readme but then thought it'd be redundant to have both there and the (eventual) website, where the readme is the main page.  I can put the examples back.

**Comment by m-clark** [comment]
added
